name: Integration Test
on: [push]
jobs:
  create_requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Requirements PC
        id: reqpc

        uses: ryan-rozario/pipreqs-action-cpy@master

        with:
          PROJECT_PATH: logiciel_pc   #default is the root of the repository
          REQUIREMENT_PATH: logiciel_pc/requirements.txt  #default is requirement.txt in the root of your repository 

      - name: Requirements PI
        id: reqpi

        uses: ryan-rozario/pipreqs-action-cpy@master

        with:
          PROJECT_PATH: logiciel_raspberry   #default is the root of the repository
          REQUIREMENT_PATH: logiciel_raspberry/requirements.txt  #default is requirement.txt in the root of your repository 
